version: "3.8" # the version of Docker Compose that we are using
services: 
  app_folder: # your service name
    build: ./app # the action to build the image
    container_name: app_container
    ports: # the ports to expose
      - "4001:4000"
    volumes: # the volumes to mount
      - ./app:/app # we could use relative path instead of absolute path
      - /app/node_modules