version: "3.8" # the version of Docker Compose that we are using
services: 
  # backend: # your service name
  #   build: ./app # the action to build the image
  #   container_name: backend_container
  #   ports: # the ports to expose
  #     - "4001:4000"
  #   volumes: # the volumes to mount
  #     - ./app:/app # we could use relative path instead of absolute path
  #     - /app/node_modules
  frontend:
    build: ./my-blog
    container_name: frontend_container
    ports:
      - "5173:5173"
    # volumes:
    #   - ./my-blog:/my-blog
    #   - /my-blog/node_modules
    # stdin_open: true
    tty: true